name: pitchupflutter
description: This library can be used to implement your own instrument tuning app.
version: 0.0.1
homepage: https://techpotatoes.github.io/pitchup-flutter/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: